name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@master

    - name: Setup VS2019
      uses: warrenbuckley/Setup-MSBuild@v1

    - name: MSBuild
      working-directory: Meduza/Sandbox/
      run: msbuild Sandbox.vcxproj
